### ISSUE TITLE
Issue with Table Of Contents when converting from docx

### ISSUE THREAD

**Issue by kerico** [sbraconnier/jodconverter#139] opened 2019-03-19 14:43 UTC
[DocxWithTOC.docx](https://github.com/sbraconnier/jodconverter/files/2983901/DocxWithTOC.docx)

Hello, I have noticed that when converting a file from docx to pdf/odt/doc while using jodconverter-cli Auotmatic table of contents does not get copied over.
Works fine when converting from doc.

Is there a workaround or does this need to be fixed?

Thank you

**Comment by kerico** [comment] 2019-03-19 14:47
P.S. converting with open office

**Comment by sbraconnier** [comment] 2019-04-04 03:11
Did you try with LibreOffice??? 

You should also try to do it without JODConverter juste to know if the problem is with JODConverter of with Open Office. If it's an Open Office issue, I can't do anything. But if the conversion succeed without JODConverter, then I may be able to investigate.

**Comment by kerico** [comment] 2019-04-04 08:39
1) I have not tried LibreOffice. 
2) I have tried converting directly through OpenOffice and it seems to work fine

**Comment by sbraconnier** [comment] 2019-04-17 03:15
It works using LibreOffice. Is it an option for you to use LibreOffice instead??

**Comment by sbraconnier** [comment] 2019-05-03 12:48
So ? Can I close this one ?

**Comment by kerico** [comment] 2019-05-03 13:20
Yes

2019-05-03, pn 15:48, Simon Braconnier <notifications@github.com> rašė:

**Comment by sbraconnier** [comment] 2019-05-03 14:03
Thanks!!!

**Closed by sbraconnier** 2019-05-03 14:03 UTC
Labels: question
