### ISSUE TITLE
type  ”Microsoft Word 97 - 2003“ 

### ISSUE THREAD

**Issue by hbbdjw** [sbraconnier/jodconverter#212] opened 2020-06-05 12:20 UTC

**Comment by hbbdjw** [comment] 2020-06-05 12:24
_When I use 4.3.0 version for word to PDF, will bring the error:_ 

org.jodconverter.core.office.OfficeException: Local conversion failed
	at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:132)
	at org.jodconverter.local.office.OfficeProcessManagerPoolEntry.doExecute(OfficeProcessManagerPoolEntry.java:187)
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:83)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: Could not open document: XX.doc
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
	at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocument(AbstractLocalOfficeTask.java:118)
2020-06-05 20:20:49 [jodconverter-poolentry-1] ERROR org.jodconverter.local.task.LocalConversionTask - Local conversion failed.
	at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:117)
java.lang.NullPointerException: Could not open document: XX.doc
	... 7 more
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222) ~[commons-lang3-3.3.2.jar:3.3.2]
	at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocument(AbstractLocalOfficeTask.java:118) ~[jodconverter-local-4.3.0.jar:4.3.0]
	at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:117) ~[jodconverter-local-4.3.0.jar:4.3.0]
	at org.jodconverter.local.office.OfficeProcessManagerPoolEntry.doExecute(OfficeProcessManagerPoolEntry.java:187) [jodconverter-local-4.3.0.jar:4.3.0]
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:83) [jodconverter-core-4.3.0.jar:4.3.0]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[na:1.8.0_66]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66]

**Comment by sbraconnier** [comment] 2020-07-15 16:16
Hmm... Could you please provide a full example to reproduce this problem ?

**Comment by sbraconnier** [comment] 2021-01-13 20:02
Closing this one since since I didn't received any feedback. Fell to re-open if required.

**Closed by sbraconnier** 2021-01-13 20:02 UTC
Labels: waiting-for-feedback
