### ISSUE TITLE
Converting doc to pdf with original formatting 

### ISSUE THREAD

**Issue by Borkau** [sbraconnier/jodconverter#258] opened 2021-04-21 12:45 UTC
Hi, 
Apologies if my problem is stupid.
I'm new to programming and your project helps me a lot, but I can't figure out that when converting doc to pdf, my text formatting changes.
For example, in the original text there were no hyphenations by syllables, and after conversion to PDF, they appear.
My implementation is quite simple:

```
    public static FileObject convertJod(DBFile file, final String toExt) {


        ByteArrayInputStream inputStream = new ByteArrayInputStream(file.getFileData());
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

        final LocalOfficeManager officeManager = LocalOfficeManager.install();
        try {
            officeManager.start();
            JodConverter
                    .convert(inputStream)
                    .as(DefaultDocumentFormatRegistry.DOC)
                    .to(outputStream)
                    .as(DefaultDocumentFormatRegistry.PDF)
                    .execute();
        } catch (OfficeException e) {
            e.printStackTrace();
        } finally {
            OfficeUtils.stopQuietly(officeManager);
        }
        final String fileName = FileUtility.getFileNameWithoutExtension(file.getFileName()) + "." + toExt;

        byte[] resultArray = outputStream.toByteArray();
        return new FileObject(fileName, MimeTypeRegistry.getMimeTypeByFileExtension(toExt), resultArray);
    }
```

**Comment by Borkau** [comment] 2021-04-21 14:19
Lol, it turned out that everything is in order, it's just that my browser adds hyphenations when viewed

**Comment by Borkau** [comment] 2021-04-21 14:27
Although no, I rechecked the problem remained.

**Comment by sbraconnier** [comment] 2021-04-22 11:54
Would it be possible for you to try that conversion, but WITHOUT jodconverter (using libre office manually) ? I need to know if the problem is jodconverter, or Libre Office.

**Comment by Borkau** [comment] 2021-04-27 11:40
Sorry for the long answer. I am using Open Office. There are no problems manually.
And one more interesting point. I tried to convert doc to docx (such as an intermediate format) and I got a null response. Using the same implementation as I wrote above.

**Comment by Khatri7yash** [comment] 2021-06-02 07:20
I'm getting error of officeHome initialization... here is the error "java.lang.NullPointerException: officeHome must not be null" can anyone please help me out as i'm unable to convert word to pdf using any classes out there...

**Comment by sbraconnier** [comment] 2022-09-09 17:49
@Khatri7yash Libre office can't be installed on android.

**Comment by sbraconnier** [comment] 2022-09-09 17:53
@Borkau I'm not sure OpenOffice offers support for docx conversion.

Anyway, I was unable to reproduce the problem. I would need the original document to work on this one. Since the issue was opened more than a year ago, I'll close it. Feel free to reopen it if needed.

**Closed by sbraconnier** 2022-09-09 17:53 UTC
Labels: question
