### ISSUE TITLE
conversion stalling on stopQuietly

### ISSUE THREAD

**Issue by AndreaGot** [sbraconnier/jodconverter#247] opened 2021-01-26 09:00 UTC
Hello, 

we are currently using jodconverter in our Angular project with a Java backend that runs on a server with both LibreOffice and OpenOffice. When it comes to converting a couple of files at once, it works like a charm.
In another implementation, though, we need to convert a (potentially) large number of xls into pdf, in response to a httprequest that sends all the relevant data.

What we noticed is that the method where the conversion is performed creates all the files involved, but never returns, stalling on _stopQuietly()_ even with just 4 or 5 files in the process. 
If we skip stopQuietly completely, conversion is successful and returns a value as expected. Moreover, a new conversion doesn't add up in system processes, because soffice.exe is closed and relaunched.

Is there a reason for _stopQuietly()_ to take so long? Is something we have to tweak in OpenOffice/LibreOffice in order for it to work?

Understanding this issue could be very useful because we would need to process way over 200 files at once, and it's difficult for us to handle that if we cannot stop and start the service in a reasonable time.

Thank you

Andrea

**Comment by sbraconnier** [comment] 2021-01-30 18:17
Hmm.... I don't understand why the `stopQuietly()` is called so often in your implementation. Are you starting a new office manager each time you need to convert a file ??? You could start only a single office manager and stop it only when your application is closed. If you want to be able to execute more than 1 conversion at the time, just set the [portNumbers](https://github.com/sbraconnier/jodconverter/wiki/Configuration#1234portnumbersandorcapital_abcdpipenames) properly.

The project contains0 a [Stress Test](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-local/src/integTest/java/org/jodconverter/local/StressITest.java) I just executed without any problem here on my windows 10 machine.

Could you explain more in details how you use jodconverter? Maybe with a bit of source code or a sample project you could share showing your problem?

**Comment by AndreaGot** [comment] 2021-02-01 14:48
Hello, 

Our application works on a REST service: User selects all the documents he wants to convert, a REST service is called executing the conversion (open manager, loop for each file requested, close manager). Of course we do not start and close a manager _on each file_, but we need to do it on each export the user might request.

Our issue is in stopQuietly, because it seems to take a long time closing the manager before returning a value to the client. We noticed that not using stopQuietly returns faster, and the following manager start closes and relaunches the manager Windows service.

At the moment it's the most efficient way we found to handle the manager..

**Comment by sbraconnier** [comment] 2021-02-01 19:25
Ok. Why don't you start the manager when the REST service is started, and close it when the service is stopped?? The users would never have to wait for the office processes to start/close. JODConverter works like a database connections pool. You don't create your pool on demand, you create it on application start.

> Of course we do not start and close a manager on each file, but we need to do it on each export the user might request.

Why is that ??

[This sample project](https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-samples/jodconverter-sample-rest) is a REST API and the manager is started only once and closed only once.

If you insist on opening and closing a manager on each request, I would need a sample project to work with that reproduces the problem.

**Comment by AndreaGot** [comment] 2021-02-04 09:30
I'll check if we can start the manager upon startup of the REST service, and I'll let you know.

Thanks

Andrea

**Comment by sbraconnier** [comment] 2021-09-16 14:31
Will close this one due to inactivity. Fell free to re-open is needed.

**Closed by sbraconnier** 2021-09-16 14:31 UTC
Labels: waiting-for-feedback
