### ISSUE TITLE
Warning: Office process died with exit code 81; restarting it

### ISSUE THREAD

**Issue by ikr0m** [sbraconnier/jodconverter#48] opened 2018-02-02 07:19 UTC
1) If I don't start libreoffice process manually (I used default port in code), jodconverter can convert file but writes warning to console:
`Warning: Office process died with exit code 81; restarting it`
Every time when I convert file I see above warning. So jodconverter starts libreoffice with default 2002 port and can convert file, but there is warning. I understand that libreoffice has not been started but 1st time warning is ok, but subsequent warnings means jodconverter always starts libreoffice not keeping it alive for future requests.

2) I start libreoffice like this manually in terminal (used 8100 port):
`libreoffice --headless --accept="socket,host=0,port=8100,tcpNoDelay=1;urp" --nodefault --nofirststartwizard --nolockcheck --nologo --norestore --invisible &`
I check that there is soffice.bin, oosplash processes are running.
I converted one file with jodconverter (first time). Everything is ok, no warning. Conversion was successful. But after conversion soffice.bin and oosplash processes are died.
I converted file again (second time). It also converted file but there was a warning! And all other future conversions had warnings. 

Following are debug logs when warning is produced:
```
11:03:36,375 [info] o.j.o.OfficeProcessManager - Submitting task 'Start' and waiting...
11:03:36,386 [info] o.j.o.OfficeProcess - Starting process with acceptString 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1'
11:03:36,403 [debug] o.j.p.AbstractProcessManager - Command line matches! Returning pid: 24961
11:03:36,403 [info] o.j.o.OfficeProcess - Started process; pid = 24961
11:03:36,403 [debug] o.j.o.OfficeConnection - Connecting with connectString 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1'
11:03:36,654 [debug] o.j.o.OfficeConnection - Connecting with connectString 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1'
11:03:36,655 [warn] o.j.o.ConnectRetryable - Office process died with exit code 81; restarting it
11:03:36,691 [info] o.j.o.OfficeProcess - Starting process with acceptString 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1'
11:03:36,710 [debug] o.j.p.AbstractProcessManager - Command line matches! Returning pid: 24981
11:03:36,710 [info] o.j.o.OfficeProcess - Started process; pid = 24981
11:03:36,960 [debug] o.j.o.OfficeConnection - Connecting with connectString 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1'
11:03:36,964 [info] o.j.o.OfficeConnection - Connected: 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1'
11:03:36,964 [debug] o.j.o.OfficeProcessManager - Task 'Start' executed successfully
11:03:36,965 [debug] o.j.o.AbstractOfficeManagerPoolEntry - Waiting for task to complete...
```
This is the code to convert file (fodt to pdf):
```
val officeManager = LocalOfficeManager.builder().portNumbers(8100).install().build()
try {
  officeManager.start()
  JodConverter
      .convert(tmpFodtFilePath.toFile)
      .to(tmpPdfFilePath.toFile)
      .execute()
} finally {
  OfficeUtils.stopQuietly(officeManager)
}
```
I'm using: Kubuntu (Ubuntu) 16.04, LibreOffice 5.1.6.2 10m0(Build:2), java 8, jodconverter 4.1.1 snapshot,

**Comment by sbraconnier** [comment] 2018-02-02 12:57
This is a know issue with OOo when the user environment doesn't exist on start. See:
https://code.google.com/archive/p/jodconverter/issues/84

Not sure why though you get this message for each conversion. It is supposed to occur only for the first start. I'll look into it.

Meanwhile, you could try to set the [templateProfileDir](https://github.com/sbraconnier/jodconverter/wiki/Configuration#file_foldertemplateprofiledir) to a copy of the default profile directory of LibreOffice:

```scala
val officeManager =
    LocalOfficeManager.builder()
        .templateProfileDir("/tmp/libreoffice/templateprofile")
        .portNumbers(8100) // or use default
        .install()
        .build()
try {
  officeManager.start()
  JodConverter
      .convert(tmpFodtFilePath.toFile)
      .to(tmpPdfFilePath.toFile)
      .execute()
} finally {
  OfficeUtils.stopQuietly(officeManager)
}
```

You can find the environment user directory in Tools/Options/LibreOffice/Paths

**Comment by ikr0m** [comment] 2018-02-04 18:53
Thanks! I'll try with `templateProfileDir` approach.

**Comment by ikr0m** [comment] 2018-02-05 05:39
After using `templateProfileDir` warning disappeared. 
But it's still killing manually started processes (`soffice.bin` and `oosplash`).
More details about issue:
1. I started libreoffice manually from terminal (tried both commands separately): 
a) `libreoffice --headless --accept="socket,host=0,port=8100,tcpNoDelay=1;urp" --nodefault --nofirststartwizard --nolockcheck --nologo --norestore --invisible &`
b) `libreoffice --headless --accept="socket,host=0,port=8100,tcpNoDelay=1;urp" --nodefault --nofirststartwizard --nolockcheck --nologo --norestore --invisible -env:UserInstallation=/home/user/tmp/libreoffice/ &`
2. This is the running processes:
```
$ top -bc -n 1 |grep office 
10166 user    20   0  200536   4444   3848 S   0.0  0.0   0:00.01 /usr/lib/libreoffice/program/oosplash --headless --accept=socket,host=0,port=8100,tcpNoDelay=1;urp --nodefault --nofirststartwizard --nolockcheck --nologo --norestore --invisible -env:UserInstallation=file:///home/user/tmp/libreoffice/
10183 user    20   0  640700  71652  46324 S   0.0  0.4   0:00.12 /usr/lib/libreoffice/program/soffice.bin -env:UserInstallation=file:///home/user/tmp/libreoffice/ --headless --accept=socket,host=0,port=8100,tcpNoDelay=1;urp --nodefault --nofirststartwizard --nolockcheck --nologo --norestore --invisible
10184 user    20   0       0      0      0 Z   0.0  0.0   0:00.00 [soffice.bin] <defunct>
10521 user    20   0   15760   1096    988 S   0.0  0.0   0:00.00 grep --color=auto office
```
3. Tried to convert (first time): 
No warning. But jodconverter started separate soffice.bin processes and killed them. Also killed one manually started process:
```
$ top -bc -n 1 |grep office 
10604 user    20   0  640636  69636  46340 S   0.0  0.4   0:00.57 /usr/lib/libreoffice/program/soffice.bin -accept=socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///tmp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
10617 user    20   0       0      0      0 Z   0.0  0.0   0:00.00 [soffice.bin] <defunct>
10641 user    20   0   15760    984    884 S   0.0  0.0   0:00.00 grep --color=auto office
```
4. Tried to convert again (second time). jodconverter created necessary soffice.bin processes, converted file and killed all processes including manually created processes. In this case after conversion there is no libreoffice processes left. 
5. Subsequent conversions are successful but everytime soffice.bin processes are created and killed after usage.

There was following warning appeared if libreoffice started manually:
`o.j.o.OfficeProcess - A process with acceptString 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager' is already running; pid 11692`

Other warnings separately:
`[warn] o.j.o.OfficeProcess - Could not delete profileDir: Unable to delete directory /tmp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1/user.; renamed it to /tmp/.jodconverter_socket_host-127.0.0.1_port-8100_tcpNoDelay-1.old.1517808397198`

`[warn] o.j.o.ConnectRetryable - Office process died with exit code 81; restarting it`

**Comment by sbraconnier** [comment] 2018-02-05 14:03
What you are experiencing seems to be the expected behavior.

A LocalOfficeManager will kill any existing process using a port it needs if the [kill switch](https://github.com/sbraconnier/jodconverter/wiki/Configuration#white_check_markkillexistingprocess) is on. If you don't want JodConverter to kill existing processes, set the kill switch to false.

I'm surprised that you are able to create 2 libreoffice processes manually listening on the same port. I don't think 2 processes can actually listen on the same port. But like I said, since [killExistingProcess](https://github.com/sbraconnier/jodconverter/wiki/Configuration#white_check_markkillexistingprocess)  is true by default, and because it will kill 1 process at the time, it is normal that it took 2 conversions to kill both of your manually started processes.

The way you described your test scenario, I think you are actually creating a new OfficeManager per conversion. If it's the case, it is also normal that soffice.bin processes are created and killed after usage. If you want to reuse the same soffice.bin, create your LocalOfficeManager when you application starts and close it only on application exit.

If you do this:

```scala
val officeManager = ...
try {
  officeManager.start()

  JodConverter.convert(sourceFile1).to(targetFile1).execute()
  JodConverter.convert(sourceFile2).to(targetFile2).execute()

} finally {
  OfficeUtils.stopQuietly(officeManager)
}
```
You will see that the same office process is used to execute both conversion.

**Comment by sbraconnier** [comment] 2018-02-17 04:38
No feedback, closing this one.

**Closed by sbraconnier** 2018-02-17 04:38 UTC

**Comment by EugenMayer** [comment] 2023-11-01 16:59
@sbraconnier a chance to reopen this on or at least discuss it? Seeing

`Office process died with exit code 81;`, more precisely 

```
2023-10-31T18:48:07.361Z  INFO 8 --- [er-offprocmng-0] o.j.l.o.LocalOfficeProcessManager        : Starting process with --accept 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1'
2023-10-31T18:48:08.253Z  WARN 8 --- [er-offprocmng-0] o.j.l.o.StartProcessAndConnectRetryable  : Office process died with exit code 81; restarting it
```

I use jodconverter to start the processes itself, see https://github.com/EugenMayer/officeconverter/blob/main/src/main/kotlin/de/kontextwork/converter/module/convert/ConverterService.kt#L26

The question is, if that is actually intended as you write above. I basically start an office process for one job? But why does it exit with non zero code (basically clean shutdown)?

Could you elaborate a bit on your POV or maybe point me where i can read up a bit more?

Thanks for the effort!

**Comment by sbraconnier** [comment] 2023-12-20 05:13
@EugenMayer Wow!! I love the kotlin version :).

So, I'll try to explain how I understand myself this `exit code 81` management, since [it's not me that introduced it](https://code.google.com/archive/p/jodconverter/issues/84).

When we launch LibreOffice, if the user env directory does not exist, LibreOffice will initialize it and exit with the code 81. It then restart with a fully initialized user env directory.

So in our context (jodconverter), since we want to be able to launch multiple instances of LibreOffice, we have to use the [-env argument](https://github.com/jodconverter/jodconverter/blob/364f589907da5d28ff82716c1b7581259cf40542/jodconverter-local/src/main/java/org/jodconverter/local/office/LocalOfficeProcessManager.java#L643) to have a single directory per process. The user env directory obviously won't exist on the first LO launch. Since it's kind of an expected error, [we don't throw an exception that will end the starting process](https://github.com/jodconverter/jodconverter/blob/master/jodconverter-local/src/main/java/org/jodconverter/local/office/StartProcessAndConnectRetryable.java#L212) but instead an exception that will tell to jodconverter to try to start the process again. On the next [start attempt](https://github.com/jodconverter/jodconverter/blob/master/jodconverter-local/src/main/java/org/jodconverter/local/office/StartProcessAndConnectRetryable.java#L95), the user env directory WILL exist so the process won't exit this time. (Also see the base [AbstractRetryable](https://github.com/jodconverter/jodconverter/blob/master/jodconverter-core/src/main/java/org/jodconverter/core/office/AbstractRetryable.java) class to understand the logic behind the process start attemps). 

> The question is, if that is actually intended as you write above. I basically start an office process for one job? But why does it exit with non zero code (basically clean shutdown)?

The anwser to that question is no if the job you are referring to is the conversion of a document. When we launch LibreOffice, it will be "kind of" be launched 2 times; the first time will only initialize the user env directory, no conversion, but then the second time it will convert as many documents as the [maxTasksPerProcess](https://github.com/jodconverter/jodconverter/wiki/Configuration#1234maxtasksperprocess) allows. When this limit is reached, the process is then restart, but without the `exit code 81` this time because [we don't delete the user env directory](https://github.com/jodconverter/jodconverter/blob/master/jodconverter-local/src/main/java/org/jodconverter/local/office/LocalOfficeProcessManager.java#L246) when we restart a process because the `maxTasksPerProcess` is reached.

I hope this clarifies things a little!

Happy holidays!!

**Comment by surli** [comment] 2025-03-20 09:18
@sbraconnier Hi, I'm coming back on this one because we have an opened ticket on our side related to it: https://jira.xwiki.org/browse/XWIKI-22567. My understanding by reading your latest comment is that it's an expected and wanted behaviour so it's not going to change. I'm fine with that, but then I'm wondering if there shouldn't be something to do to avoid having systematically the warning: I mean, it makes sense to display a warning if let's say there's the 81 error code at second attempt, because it's not expected. But on first attempt, as you explain it is expected, so IMO if we could just have a check on the number of attempts and maybe just display a debug info instead of a warning in that case it would avoid a lot the WTF effect of this log. wdyt?

**Comment by sbraconnier** [comment] 2025-03-20 12:14
I totally agree. It is this kind of thing that was already in place when I took over the project and didn't think any further about it. It makes sense to just display a debug info. I'll change it for the next release.

**Comment by surli** [comment] 2025-06-13 14:01
@sbraconnier I just realized that there was a release last month and I think the issue is still there?
