### ISSUE TITLE
why is error?

### ISSUE THREAD

**Issue by ruanzy** [sbraconnier/jodconverter#161] opened 2019-08-20 03:01 UTC
```java
File inputFile = new File("e:/aaa.docx");
File outputFile = new File("e:/abc/document.pdf");	
final OnlineOfficeManager officeManager = OnlineOfficeManager.make("http://ip:8100");
officeManager.start();
OnlineConverter.make(officeManager).convert(inputFile).to(outputFile).execute();
```

**Comment by Eucly2** [comment] 2019-10-14 14:03
Hi!
Yes i have this error with this code:

`Caused by: java.lang.IllegalArgumentException: @JsonAdapter value must be TypeAdapter or TypeAdapterFactory reference.
	at com.google.gson.internal.bind.JsonAdapterAnnotationTypeAdapterFactory.getTypeAdapter(JsonAdapterAnnotationTypeAdapterFactory.java:64)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:119)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:46)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:92)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:91)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:142)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:83)
	at com.google.gson.Gson.getAdapter(Gson.java:359)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:52)
	at com.google.gson.Gson.getAdapter(Gson.java:359)
	at com.google.gson.Gson.fromJson(Gson.java:809)
	at com.google.gson.Gson.fromJson(Gson.java:775)
	at com.google.gson.Gson.fromJson(Gson.java:724)
	at org.jodconverter.document.JsonDocumentFormatRegistry.readJsonArray(JsonDocumentFormatRegistry.java:107)
	at org.jodconverter.document.JsonDocumentFormatRegistry.create(JsonDocumentFormatRegistry.java:90)
	at org.jodconverter.document.JsonDocumentFormatRegistry.create(JsonDocumentFormatRegistry.java:65)
	at org.jodconverter.document.JsonDocumentFormatRegistry.create(JsonDocumentFormatRegistry.java:50)
	at org.jodconverter.document.DefaultDocumentFormatRegistryInstanceHolder.getInstance(DefaultDocumentFormatRegistryInstanceHolder.java:45)
	at org.jodconverter.document.DefaultDocumentFormatRegistry.getInstance(DefaultDocumentFormatRegistry.java:400)
	at org.jodconverter.document.DefaultDocumentFormatRegistry.<clinit>(DefaultDocumentFormatRegistry.java:52)`

**Comment by sbraconnier** [comment] 2020-01-16 03:27
Do you still have this problem ?? I suspect it was a dependency problem. Maybe your project was not properly set.

**Comment by sbraconnier** [comment] 2020-01-30 21:00
@Eucly2 
Closing this one for now since i'm unable to reproduce it. Fell free to reopen it with more details.

**Closed by sbraconnier** 2020-01-30 21:00 UTC
Labels: question

**Comment by hlizard** [comment] 2022-08-30 09:15
> Hi! Yes i have this error with this code:
> 
> `Caused by: java.lang.IllegalArgumentException: @JsonAdapter value must be TypeAdapter or TypeAdapterFactory reference. at com.google.gson.internal.bind.JsonAdapterAnnotationTypeAdapterFactory.getTypeAdapter(JsonAdapterAnnotationTypeAdapterFactory.java:64) at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:119) at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:46) at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:92) at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:91) at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:142) at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:83) at com.google.gson.Gson.getAdapter(Gson.java:359) at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:52) at com.google.gson.Gson.getAdapter(Gson.java:359) at com.google.gson.Gson.fromJson(Gson.java:809) at com.google.gson.Gson.fromJson(Gson.java:775) at com.google.gson.Gson.fromJson(Gson.java:724) at org.jodconverter.document.JsonDocumentFormatRegistry.readJsonArray(JsonDocumentFormatRegistry.java:107) at org.jodconverter.document.JsonDocumentFormatRegistry.create(JsonDocumentFormatRegistry.java:90) at org.jodconverter.document.JsonDocumentFormatRegistry.create(JsonDocumentFormatRegistry.java:65) at org.jodconverter.document.JsonDocumentFormatRegistry.create(JsonDocumentFormatRegistry.java:50) at org.jodconverter.document.DefaultDocumentFormatRegistryInstanceHolder.getInstance(DefaultDocumentFormatRegistryInstanceHolder.java:45) at org.jodconverter.document.DefaultDocumentFormatRegistry.getInstance(DefaultDocumentFormatRegistry.java:400) at org.jodconverter.document.DefaultDocumentFormatRegistry.<clinit>(DefaultDocumentFormatRegistry.java:52)`

same error(because use gson 2.3.1), gson 2.8.9 works!
