### ISSUE TITLE
about blank xls file can not be converter

### ISSUE THREAD

**Issue by freebie5** [sbraconnier/jodconverter#199] opened 2020-03-11 09:22 UTC
hello Simon,
today, when I try to converter a blank file(xls,xlsx), it throws a exception below:

org.jodconverter.core.office.OfficeException: Could not store document: tt.pdf; errorCode: 3088

and then, I try find out why, this exception location on 

org.jodconverter.local.task.LocalConversionTask.storeDocument(LocalConversionTask.java:183)

it is seem to be can not load the file inputstream.

I wonder if you could help me with this.

**Comment by sbraconnier** [comment] 2020-03-12 05:46
I tried here but were unable to reproduce the problem. I tried with a new blank valid xls. I also tried with an empty file (0 byte) with an xls extension. Both succeeded.

What is your version of LibreOffice or OpenOffice ?

**Comment by sbraconnier** [comment] 2020-03-12 05:49
After a lot of reading, I may be because you don't have enough permission to write in the destination folder...

Try googling for the errorCode: 3088 with LibreOffice.

**Comment by freebie5** [comment] 2020-03-12 06:23
thanks，Simon！

  an empty file(0 byte) with xls, xlsx, pptx extension is  can not be converted, also a new blank valid xls, xlsx, pptx is can not be converted too!

  yesterday, I am sorry to bother you, I work for this question hold day too...

  my local environment is installed: Apache_OpenOffice_4.1.7_Win_x86_install_zh-CN.exe

  my pro environment is installed: Apache_OpenOffice_4.1.7_Linux_x86-64_install-rpm_zh-CN.tar.gz

  both environment is unable to convert

  and my jar lib is: 
        <dependency>
            <groupId>org.jodconverter</groupId>
            <artifactId>jodconverter-local</artifactId>
            <version>4.3.0</version>
        </dependency>
  
  I hope this information of my environment is useful for you.

**Comment by freebie5** [comment] 2020-03-12 06:29
ps:
I am sure my program has enough permission to write an new pdf file.

when I run the same program with others file(doc, docx, ppt, all is new blank vaild file, or empty 0 byte file), the program can convert the file to pdf.

so, I think it is not because of the permission.

**Comment by freebie5** [comment] 2020-03-12 06:35
14:35:14.221 [main] DEBUG org.jodconverter.local.office.LocalOfficeUtils - Default office home set to C:\Program Files (x86)\OpenOffice 4
14:35:14.370 [main] INFO org.jodconverter.local.office.OfficeProcessManager - Submitting task 'Start' and waiting...
14:35:14.536 [jodconverter-officeprocess-0] DEBUG org.jodconverter.local.process.AbstractProcessManager - No matching command line found! Returning pid: NOT_FOUND
14:35:14.536 [jodconverter-officeprocess-0] DEBUG org.jodconverter.local.office.OfficeProcess - Checking existing process done successfully. No process running with --accept 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager'
14:35:14.539 [jodconverter-officeprocess-0] INFO org.jodconverter.local.office.OfficeDescriptor - soffice info (from exec path): Product: OpenOffice - Version: ??? - useLongOptionNameGnuStyle: false
14:35:14.540 [jodconverter-officeprocess-0] DEBUG org.jodconverter.local.office.OfficeProcess - ProcessBuilder command: C:\Program Files (x86)\OpenOffice 4\program\soffice.exe -accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager -headless -invisible -nocrashreport -nodefault -nofirststartwizard -nolockcheck -nologo -norestore -env:UserInstallation=file:///C:/Users/HUANGS~1/AppData/Local/Temp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1
14:35:14.540 [jodconverter-officeprocess-0] INFO org.jodconverter.local.office.OfficeProcess - OFFICE HOME: C:\Program Files (x86)\OpenOffice 4
14:35:14.540 [jodconverter-officeprocess-0] INFO org.jodconverter.local.office.OfficeProcess - Starting process with --accept 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir 'C:\Users\HUANGS~1\AppData\Local\Temp\.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1'
14:35:14.547 [jodconverter-officeprocess-0] DEBUG org.jodconverter.local.office.StartProcessRetryable - Trying to find pid, attempt #1
14:35:14.759 [jodconverter-officeprocess-0] DEBUG org.jodconverter.local.process.AbstractProcessManager - Command line matches! Returning pid: 13640
14:35:14.759 [jodconverter-officeprocess-0] INFO org.jodconverter.local.office.OfficeProcess - Started process; pid: 13640
14:35:14.760 [jodconverter-officeprocess-0] DEBUG org.jodconverter.local.office.OfficeConnection - Connecting with connectString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
14:35:15.462 [jodconverter-officeprocess-0] INFO org.jodconverter.local.office.OfficeConnection - Connected: 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
14:35:15.463 [main] DEBUG org.jodconverter.local.office.OfficeProcessManager - Task executed successfully: Start
14:35:15.897 [main] DEBUG org.jodconverter.core.office.AbstractOfficeManagerPoolEntry - Waiting for task to complete: LocalConversionTask{source=SourceDocumentSpecsFromFile{file=Optional[blank.xlsx], format=xlsx}, loadProperties=null, target=TargetDocumentSpecsFromFile{file=Optional[blank.pdf], format=pdf}, storeProperties=null}
14:35:15.898 [jodconverter-poolentry-1] INFO org.jodconverter.local.task.LocalConversionTask - Executing local conversion task [xlsx -> pdf]...
14:35:15.980 [jodconverter-poolentry-1] ERROR org.jodconverter.local.task.LocalConversionTask - Local conversion failed.
org.jodconverter.core.office.OfficeException: Could not open document: blank.xlsx
	at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocument(AbstractLocalOfficeTask.java:126)
	at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:117)
	at org.jodconverter.local.office.OfficeProcessManagerPoolEntry.doExecute(OfficeProcessManagerPoolEntry.java:187)
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:83)
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry$$Lambda$22/1497973285.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.sun.star.lang.IllegalArgumentException: URL seems to be an unsupported one.
	at com.sun.star.lib.uno.environments.remote.Job.remoteUnoRequestRaisedException(Job.java:173)
	at com.sun.star.lib.uno.environments.remote.Job.execute(Job.java:139)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:334)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:303)
	at com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:87)
	at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:636)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:146)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:128)
	at com.sun.proxy.$Proxy4.loadComponentFromURL(Unknown Source)
	at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocument(AbstractLocalOfficeTask.java:114)
	... 8 common frames omitted
14:35:15.985 [main] INFO org.jodconverter.core.office.AbstractOfficeManagerPool - Stopping the office manager pool...
14:35:15.985 [main] INFO org.jodconverter.local.office.OfficeProcessManager - Submitting task 'Stop' and waiting...
14:35:15.990 [jodconverter-officeprocess-0] DEBUG org.jodconverter.local.office.OfficeProcessManager - The Office Process has been terminated
14:35:15.996 [MessageDispatcher] INFO org.jodconverter.local.office.OfficeConnection - Disconnected: 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'
14:35:16.240 [jodconverter-officeprocess-0] INFO org.jodconverter.local.office.OfficeProcessManager - Process exited with code 0
14:35:16.240 [jodconverter-officeprocess-0] DEBUG org.jodconverter.local.office.OfficeProcess - Deleting instance profile directory 'C:\Users\HUANGS~1\AppData\Local\Temp\.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1'
Exception in thread "main" 14:35:16.280 [main] DEBUG org.jodconverter.local.office.OfficeProcessManager - Task executed successfully: Stop
org.jodconverter.core.office.OfficeException: Could not open document: blank.xlsx
14:35:16.280 [main] INFO org.jodconverter.core.office.AbstractOfficeManagerPool - Office manager stopped
	at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocument(AbstractLocalOfficeTask.java:126)
	at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:117)
14:35:16.280 [main] DEBUG org.jodconverter.core.office.AbstractOfficeManager - Deleting temporary directory 'C:\Users\HUANGS~1\AppData\Local\Temp\jodconverter_25773abc-5e80-4bd8-80d2-5837beda2f85'
	at org.jodconverter.local.office.OfficeProcessManagerPoolEntry.doExecute(OfficeProcessManagerPoolEntry.java:187)
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:83)
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry$$Lambda$22/1497973285.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.sun.star.lang.IllegalArgumentException: URL seems to be an unsupported one.
	at com.sun.star.lib.uno.environments.remote.Job.remoteUnoRequestRaisedException(Job.java:173)
	at com.sun.star.lib.uno.environments.remote.Job.execute(Job.java:139)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:334)
	at com.sun.star.lib.uno.environments.remote.JobQueue.enter(JobQueue.java:303)
	at com.sun.star.lib.uno.environments.remote.JavaThreadPool.enter(JavaThreadPool.java:87)
	at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge.sendRequest(java_remote_bridge.java:636)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.request(ProxyFactory.java:146)
	at com.sun.star.lib.uno.bridges.java_remote.ProxyFactory$Handler.invoke(ProxyFactory.java:128)
	at com.sun.proxy.$Proxy4.loadComponentFromURL(Unknown Source)
	at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocument(AbstractLocalOfficeTask.java:114)
	... 8 more

**Comment by sbraconnier** [comment] 2020-03-12 11:57
Is it possible for you to try with a recent version of LibreOffice in your local environment? I would like to know if the problem is related to the office installation, or with the uno libraries.

**Comment by sbraconnier** [comment] 2020-03-12 12:00
Nevermind... I tried with OpenOffice 4.1.6 and got the problem... So it is related to the OpenOffice.

Is it possible for you to use LibreOffice or is it out of question ??

**Comment by freebie5** [comment] 2020-03-12 12:08
maybe I should try install libreoffice.

I try to convert blank xls file by openoffice, it alert a error dialog too.

so I thing it is bug of openoffice

**Comment by sbraconnier** [comment] 2020-03-12 12:11
I also try directly with OO (without JODConverter) using the File/Export menu and got the same error. So I think that this is really a bug with OO. There's nothing I can do here.

![OO Blank Error](https://user-images.githubusercontent.com/15372565/76520183-d30cd080-6438-11ea-90a0-a098b6fa3843.PNG)

**Comment by sbraconnier** [comment] 2020-03-12 12:12
Ah! You tried too! So I'll close this one.

**Closed** 2020-03-12 12:14 UTC
Labels: bug OO, wontfix

**Comment by freebie5** [comment] 2020-03-12 12:15
after all, thanks for you help.

**Comment by freebie5** [comment] 2020-03-12 12:20
I will try install libreoffice , and hope our discussion is   useful for others who got this exception too
