### ISSUE TITLE
libreoffice Connection failed

### ISSUE THREAD

**Issue by shiguangnan** [sbraconnier/jodconverter#172] opened 2019-10-10 12:40 UTC
hi  I have a problem when connection libreoffice .Can you help me? thank you 
usage:
```java
OfficeManager manager =
    LocalOfficeManager.builder()
        .portNumbers(2002)
        .officeHome("/usr/lib/LibreOffice")
        .install()
        .build();

manager.start();

JodConverter.convert(IOUtils.toInputStream(sb.toString()))
        .as(DefaultDocumentFormatRegistry.HTML)
        .to(innerOutputStream)
        .as(DefaultDocumentFormatRegistry.PDF)
        .execute();

manager.stop();
```
the libreoffice  server is running and listening to 2002
/ # netstat -anp|grep 2002
tcp        0      0 127.0.0.1:2002          0.0.0.0:*               LISTEN      144/soffice.bin

problem:

Caused by: org.jodconverter.office.OfficeException: Could not establish connection
        at org.jodconverter.office.OfficeProcessManager.doStartProcessAndConnect(OfficeProcessManager.java:110)
        at org.jodconverter.office.OfficeProcessManager.access$100(OfficeProcessManager.java:40)
        at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:261)
        at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:256)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.jodconverter.office.RetryTimeoutException: org.jodconverter.office.OfficeConnectionException: Connection failed: 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'; null
        at org.jodconverter.office.AbstractRetryable.execute(AbstractRetryable.java:64)
        at org.jodconverter.office.ConnectRetryable.execute(ConnectRetryable.java:26)
        at org.jodconverter.office.OfficeProcessManager.doStartProcessAndConnect(OfficeProcessManager.java:104)
        ... 7 common frames omitted
Caused by: org.jodconverter.office.OfficeConnectionException: Connection failed: 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'; null
        at org.jodconverter.office.OfficeConnection.connect(OfficeConnection.java:170)
        at org.jodconverter.office.ConnectRetryable.attempt(ConnectRetryable.java:61)
        at org.jodconverter.office.AbstractRetryable.execute(AbstractRetryable.java:57)
        ... 9 common frames omitted
Caused by: com.sun.star.lang.IllegalArgumentException: null
        at com.sun.star.comp.bridgefactory.BridgeFactory.createBridge(BridgeFactory.java:135)
        at org.jodconverter.office.OfficeConnection.connect(OfficeConnection.java:118)
        ... 11 common frames omitted

**Comment by sbraconnier** [comment] 2020-01-08 16:22
Sorry for the delay.

Did you start the office server yourself? You are suppose to let JodConverter start the Office instance.

**Comment by sbraconnier** [comment] 2020-01-30 21:04
@shiguangnan 
Closing this one for now since i'm unable to reproduce it. Fell free to reopen it with more details.

**Closed by sbraconnier** 2020-01-30 21:04 UTC
Labels: question
